[features]
seeds = false
[programs.devnet]
gif_portal_contract = "7fPRhd6Qty9yEYnMafku5EzoQRvj3PCqFMUpTbPne7WQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/berzan/.config/solana/id.json"

[scripts]
test = "yarn ts-node tests/gif-portal-contract.ts"
