[features]
seeds = false
[programs.localnet]
gif_portal_contract = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/berzan/.config/solana/id.json"

[scripts]
test = "ts-node tests/myepicproject.js"
